# -*- coding: utf-8 -*-
"""Translator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qfSqoQpiZeVDOnRN_Kxxzqr7nvr8YgSa
"""

! pip install git+https://github.com/huggingface/transformers -q

from transformers import pipeline

Translate = pipeline("translation", model="Helsinki-NLP/opus-mt-en-hi")

text = Translate("My Name is Afham")

text
