# -*- coding: utf-8 -*-
"""Translator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qfSqoQpiZeVDOnRN_Kxxzqr7nvr8YgSa
"""

!pip install streamlit
!pip install googletrans==4.0.0-rc1

from googletrans import Translator
import streamlit as st

def translate_to_hindi(text):
    translator = Translator()
    translated_text = translator.translate(text, src='en', dest='hi').text
    return translated_text

def main():
    st.title("English to Hindi Translator")
    input_text = st.text_input("Enter English text to translate:")

    if st.button("Translate"):
        if input_text:
            translated_text = translate_to_hindi(input_text)
            st.success("Translated Text (Hindi):")
            st.write(translated_text)
        else:
            st.warning("Please enter some text to translate.")

if __name__ == "__main__":
    main()